server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ {
    proxy_pass https://todo-app-production-afcc.up.railway.app;
    proxy_ssl_server_name on;
    proxy_set_header Host todo-app-production-afcc.up.railway.app;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 30s;
    proxy_read_timeout 900s;
    proxy_send_timeout 900s;
    proxy_buffering off;
  }
  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache";
  }
}
