import SwiftUI
import SwiftData
import QuickLook

struct DeliverablesCenterView: View {
    @EnvironmentObject private var app: AppModel
    @Query(sort: \AuroraProject.updatedAt, order: .reverse) private var projects: [AuroraProject]
    @State private var selectedProjectID: UUID?
    @State private var nativePDF: URL?
    @State private var nativeCSV: URL?
    @State private var previewURL: URL?

    private var project: AuroraProject? {
        if let selectedProjectID, let selected = projects.first(where: { $0.id == selectedProjectID }) { return selected }
        return projects.first
    }

    private var artifacts: [ArtifactLink] { ResultTools.artifacts(app.activeResult) }

    private let serverFormats: [ExportFormat] = [
        .init(id: "pdf", title: "Industrial PDF", subtitle: "Governed project report", icon: "doc.richtext.fill"),
        .init(id: "xlsx", title: "Excel Workbook", subtitle: "Tables, balances and results", icon: "tablecells.fill"),
        .init(id: "docx", title: "Word Report", subtitle: "Editable engineering report", icon: "doc.text.fill"),
        .init(id: "csv", title: "CSV Data", subtitle: "Machine-readable result tables", icon: "list.bullet.rectangle.fill"),
        .init(id: "bundle", title: "Project Bundle", subtitle: "Combined governed ZIP package", icon: "archivebox.fill")
    ]

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 18) {
                hero
                projectSelector
                governedExports
                exportState
                artifactManifest
                nativeFallbacks
                authorityNote
            }
            .padding(22)
        }
        .background(AuroraTheme.background)
        .quickLookPreview($previewURL)
    }

    private var hero: some View {
        AuroraCard {
            HStack(alignment: .top, spacing: 16) {
                ZStack {
                    RoundedRectangle(cornerRadius: 18, style: .continuous)
                        .fill(AuroraTheme.accent.opacity(0.16))
                        .frame(width: 68, height: 68)
                    Image(systemName: "archivebox.fill")
                        .font(.system(size: 28, weight: .bold))
                        .foregroundStyle(AuroraTheme.accent)
                }
                VStack(alignment: .leading, spacing: 5) {
                    Text("Industrial Deliverables Center").font(.largeTitle.bold())
                    Text("Governed PDF · Excel · Word · CSV · engineering bundle")
                        .foregroundStyle(AuroraTheme.accent)
                    Text("Server exports are generated from the active AURORA project/result package. Native iOS PDF/CSV are clearly separated as local summaries.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                StatusBadge(text: app.activeResult == nil ? "No active result" : "Result available")
            }
        }
    }

    private var projectSelector: some View {
        AuroraCard {
            HStack(spacing: 12) {
                VStack(alignment: .leading, spacing: 3) {
                    Text("Delivery Basis").font(.headline)
                    Text("Select the project bound to the export package")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                if projects.isEmpty {
                    StatusBadge(text: "Create project first")
                } else {
                    Picker(
                        "Project",
                        selection: Binding<UUID?>(
                            get: { selectedProjectID ?? projects.first?.id },
                            set: { selectedProjectID = $0 }
                        )
                    ) {
                        ForEach(projects) { item in Text(item.name).tag(Optional(item.id)) }
                    }
                    .labelsHidden()
                    .frame(maxWidth: 300)
                }
            }
        }
    }

    private var governedExports: some View {
        AuroraCard {
            VStack(alignment: .leading, spacing: 12) {
                HStack {
                    VStack(alignment: .leading, spacing: 3) {
                        Text("Server-Governed Deliverables").font(.headline)
                        Text("Generated by the canonical AURORA backend export route")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                    StatusBadge(text: app.isExporting ? "Exporting" : "Ready")
                }

                LazyVGrid(columns: [GridItem(.adaptive(minimum: 210), spacing: 12)], spacing: 12) {
                    ForEach(serverFormats) { format in
                        Button {
                            guard let project else { return }
                            app.export(project: project, format: format.id)
                        } label: {
                            VStack(alignment: .leading, spacing: 10) {
                                HStack {
                                    Image(systemName: format.icon)
                                        .font(.title3.bold())
                                        .foregroundStyle(AuroraTheme.accent)
                                    Spacer()
                                    Image(systemName: "arrow.down.circle.fill")
                                        .foregroundStyle(AuroraTheme.gold)
                                }
                                Text(format.title).font(.headline).foregroundStyle(.primary)
                                Text(format.subtitle)
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                                    .multilineTextAlignment(.leading)
                            }
                            .padding(14)
                            .frame(maxWidth: .infinity, minHeight: 130, alignment: .topLeading)
                            .background(AuroraTheme.panel2, in: RoundedRectangle(cornerRadius: 15))
                        }
                        .buttonStyle(.plain)
                        .disabled(project == nil || app.isExporting)
                    }
                }
            }
        }
    }

    @ViewBuilder
    private var exportState: some View {
        if let error = app.lastError {
            AuroraCard {
                HStack(alignment: .top, spacing: 10) {
                    Image(systemName: "exclamationmark.triangle.fill").foregroundStyle(AuroraTheme.bad)
                    VStack(alignment: .leading, spacing: 4) {
                        Text("Export error").font(.headline)
                        Text(error).font(.caption.monospaced()).foregroundStyle(.secondary)
                    }
                }
            }
        }

        if let url = app.lastExportURL {
            AuroraCard {
                HStack(spacing: 12) {
                    Image(systemName: "checkmark.seal.fill").foregroundStyle(AuroraTheme.good)
                    VStack(alignment: .leading, spacing: 3) {
                        Text(app.lastExportName ?? url.lastPathComponent).font(.headline)
                        Text(url.path).font(.caption2.monospaced()).foregroundStyle(.secondary).lineLimit(2)
                    }
                    Spacer()
                    Button("Preview") { previewURL = url }
                        .buttonStyle(.bordered)
                    ShareLink(item: url) {
                        Label("Share", systemImage: "square.and.arrow.up")
                    }
                    .buttonStyle(.borderedProminent)
                }
            }
        }
    }

    private var artifactManifest: some View {
        AuroraCard {
            VStack(alignment: .leading, spacing: 12) {
                HStack {
                    VStack(alignment: .leading, spacing: 3) {
                        Text("Runtime Artifact Manifest").font(.headline)
                        Text("Files and deliverables referenced by the active result")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                    Text("\(artifacts.count) artifacts")
                        .font(.caption.monospaced())
                        .foregroundStyle(AuroraTheme.gold)
                }

                if artifacts.isEmpty {
                    ContentUnavailableView(
                        "No artifact links reported",
                        systemImage: "doc.badge.ellipsis",
                        description: Text("Run AURORA or generate a governed engineering/export package. No placeholder files are shown.")
                    )
                    .frame(maxWidth: .infinity, minHeight: 180)
                } else {
                    ForEach(artifacts.prefix(30)) { artifact in
                        HStack(alignment: .top, spacing: 10) {
                            Text(artifact.format)
                                .font(.caption2.bold())
                                .foregroundStyle(AuroraTheme.background)
                                .padding(.horizontal, 8)
                                .padding(.vertical, 5)
                                .background(AuroraTheme.gold, in: Capsule())
                            VStack(alignment: .leading, spacing: 3) {
                                Text(artifact.label).font(.caption.bold())
                                Text(artifact.raw)
                                    .font(.caption2.monospaced())
                                    .foregroundStyle(.secondary)
                                    .textSelection(.enabled)
                                    .lineLimit(3)
                            }
                            Spacer()
                        }
                        .padding(.vertical, 4)
                        Divider().opacity(0.12)
                    }
                }
            }
        }
    }

    private var nativeFallbacks: some View {
        AuroraCard {
            VStack(alignment: .leading, spacing: 12) {
                HStack {
                    VStack(alignment: .leading, spacing: 3) {
                        Text("Native Device Summaries").font(.headline)
                        Text("Offline convenience outputs; not replacements for governed server reports")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                    Text("LOCAL").font(.caption2.bold()).foregroundStyle(AuroraTheme.warn)
                }

                HStack(spacing: 10) {
                    Button {
                        guard let project else { return }
                        nativePDF = NativeReport.makePDF(project: project, result: app.activeResult)
                    } label: {
                        Label("Create local PDF summary", systemImage: "doc.fill")
                    }
                    .buttonStyle(.bordered)
                    .disabled(project == nil)

                    Button {
                        nativeCSV = NativeReport.makeCSV(result: app.activeResult)
                    } label: {
                        Label("Create local CSV", systemImage: "tablecells")
                    }
                    .buttonStyle(.bordered)
                }

                if let nativePDF {
                    HStack {
                        Text(nativePDF.lastPathComponent).font(.caption.monospaced())
                        Spacer()
                        Button("Preview") { previewURL = nativePDF }
                        ShareLink(item: nativePDF) { Image(systemName: "square.and.arrow.up") }
                    }
                }
                if let nativeCSV {
                    HStack {
                        Text(nativeCSV.lastPathComponent).font(.caption.monospaced())
                        Spacer()
                        ShareLink(item: nativeCSV) { Label("Share CSV", systemImage: "square.and.arrow.up") }
                    }
                }
            }
        }
    }

    private var authorityNote: some View {
        AuroraCard {
            HStack(alignment: .top, spacing: 12) {
                Image(systemName: "shield.checkered").foregroundStyle(AuroraTheme.gold)
                VStack(alignment: .leading, spacing: 4) {
                    Text("Delivery authority").font(.subheadline.bold())
                    Text("A deliverable is treated as governed only when produced or explicitly referenced by the AURORA runtime/export service. Local summaries remain marked as native device outputs.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }
        }
    }
}

private struct ExportFormat: Identifiable {
    let id: String
    let title: String
    let subtitle: String
    let icon: String
}
